spring: # 운영 환경
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-project
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # IN절 파라미터 개수
        default_batch_fetch_size : 16
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

decorator.datasource.p6spy.enable-logging: true